### PR TITLE
feat: add `cloudavenue_vdc_group` resource

### PR DESCRIPTION
**Pull request by azrod**
### Description of your changes

If you submit change in the provider code, please make sure to:

- [x] Write or modify examples in `examples/` directory
- [x] Write or modify acceptance tests
- [x] Run `make generate` to ensure the doc was updated properly

### CODE REVIEW

**Comment by valentin-dubreuil** [comment]
Ressource not found, please check the name of the ressource

**Comment by valentin-dubreuil** [comment]
Acceptance Test passed : ok  	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vapp	52.757s

**Comment by valentin-dubreuil** [comment]
Ressource not found, please check the name of the ressource

**Comment by valentin-dubreuil** [comment]
Ressource not found, please check the name of the ressource

**Review by dmicheneau — APPROVED** [review]

**Pull request merged**
